# Random Sampling with NumPy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.11606695])

In [3]:
np.random.random((3,3))

array([[0.24385351, 0.17578335, 0.35324019],
       [0.63076863, 0.09721975, 0.4305239 ],
       [0.63868043, 0.35324653, 0.33445603]])

In [4]:
np.random.randint(1,4)

2

In [5]:
np.random.randint(1,4, (4,4))

array([[3, 3, 2, 2],
       [2, 2, 3, 2],
       [3, 3, 3, 3],
       [2, 2, 1, 1]])

In [6]:
np.random.randint(1,4, (2,4,4))

array([[[2, 3, 1, 1],
        [1, 3, 1, 3],
        [2, 1, 2, 2],
        [1, 2, 1, 3]],

       [[1, 1, 2, 3],
        [2, 3, 2, 3],
        [1, 3, 1, 2],
        [2, 1, 2, 2]]])

In [7]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
2**32-1

4294967295

In [10]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [11]:
np.random.rand()

0.5839013656536759

In [12]:
np.random.rand(3,3)

array([[0.18263144, 0.82608225, 0.10540183],
       [0.28357668, 0.06556327, 0.05644419],
       [0.76545582, 0.01178803, 0.61194334]])

In [13]:
np.random.randn(3,3)

array([[ 0.67893119, -1.91355421, -0.94245806],
       [-1.74554298, -1.02094527, -0.16206903],
       [-0.6579709 ,  0.42211306,  0.62402334]])

In [14]:
x = [1,2,3,4]
np.random.choice(x)

1

In [15]:
np.random.choice(x)

1

In [16]:
np.random.choice(x)

3

In [17]:
np.random.choice(x)

1

In [18]:
for i in range(20):
    print(np.random.choice(x))

3
3
1
4
2
1
4
2
3
3
2
3
3
4
1
1
1
1
3
3


In [19]:
x

[1, 2, 3, 4]

In [20]:
np.random.permutation(x)

array([1, 3, 4, 2])

In [21]:
np.random.permutation(x)

array([2, 3, 4, 1])

In [22]:
np.random.permutation(x)

array([1, 3, 4, 2])