In [1]:
import numpy as np

In [2]:
mtx1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mtx1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mtx1 = np.ones(5)
print(mtx1)

[1. 1. 1. 1. 1.]


In [4]:
mtx1.dtype

dtype('float64')

In [5]:
mtx1 = np.ones((3,4))
print(mtx1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
mtx1 = np.ones((3,4), dtype = int)
print(mtx1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mtx0 = np.zeros((4,6))
print(mtx0)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
mtx0 = np.zeros((4,6), dtype=bool)
print(mtx0)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [9]:
mtx0 = np.zeros((4,6), dtype=str)
print(mtx0)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [10]:
em_str = ''
print(bool(em_str))

False


In [11]:
em_mtx = np.empty((3,3))
print(em_mtx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.51377261e-321]
 [1.33979270e-277 7.58633659e-270 8.45528067e-307]]
